// <auto-generated />
namespace MvcEasyUI160128.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateArFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateArFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201602170946055_updateArFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
