// <auto-generated />
namespace MvcEasyUI160128.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_functionclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_functionclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201602160811078_add_functionclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
